name: CI

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run tests
        run: yarn test
      - name: build
        run: yarn build
